### ISSUE TITLE
New business rule required

### ISSUE THREAD

**Issue by lemendoza** [dianmoli98/ISII-WORKSHOPS-CLUB_POOL#9]
**Is your feature request related to a problem? Please describe.**

This feature is not related to a problem. It is related to a new policy of the organization. 

Based on the impact of the pandemic in the 2020 results, the board of the company has approved a new business rule (policy) beginning january 2021, that needs to be included in our product.

**Describe the solution you'd like**

The new business rule establishes: If the customer is male, over 25 and younger than 45 then it is needed to subtract $100 from the base premium.

Therefore, we ask you to modify the premium calculation adding this new rule.

**Describe alternatives you've considered**

There is no alternative to be considered.

**Additional context**

I will provide you with more information if needed

Best regards,

LEMM

**Comment by thsam** [comment]
#“We will proceed to process
the request,  @thsam will be the assigned analyst, @thsam   will develop the solution, and
@Diermanio   will perform the tests”.

**Comment by thsam** [comment]
The impact analysis has been carried out, an approximate 8 hours is estimated to add the new requirement to the system because the new conditional must be added to the function in charge of calculating the premium and performing the respective integration tests

**Comment by thsam** [comment]
The impact analysis has been carried out, an approximate 8 hours is estimated to add the new requirement to the system because the new conditional must be added to the function in charge of calculating the premium and performing the respective integration tests

**Comment by lemendoza** [comment]
Where is the short analysis report?

**Comment by thsam** [comment]
To solve the new requirement @thsam  you will use your computer, with the respective tools: Windows 10, IDE Eclipse version 2020, Gradle and JUnit as testing tools. To add the new requirement rule, we will have to make an update to the raw material conditionals encoded in the CarInsurance.java file. The new condition will be added within the calculation function
new rule : "If the customer is male, over 25 and younger than 45 then it is needed to subtract $100 from the base premium."
The allotted time to update approximately 5 hours which includes the process of testing and customer acceptance.
@Diermanio  will perform the tests.

By presenting this analysis, does the client agree?
Good day

**Comment by lemendoza** [comment]
Ok, proceed.

**Comment by lemendoza** [comment]
Sorry. Yes, I agree.

**Comment by thsam** [comment]
https://github.com/dianmoli98/ISII-WORKSHOPS-CLUB_POOL/blob/91e8aa1f807a2bbb8eac50806a78c1922737e3d6/ec.espol.edu.workshops.second/src/main/java/ec/espol/edu/workshops/second/CarInsurance.java#L78-L81

**Comment by Diermanio** [comment]
@lemendoza here is our test plan, please tell me if you agree with what is proposed and if so, if you want to evaluate the test cases
[Testing_Plan.docx](https://github.com/dianmoli98/ISII-WORKSHOPS-CLUB_POOL/files/5846981/Testing_Plan.docx)
#

**Comment by lemendoza** [comment]
Yes, I agree. Please, perform the tests and let me know the results.

**Comment by Diermanio** [comment]
@lemendoza here are our results from our test plan previously accepted, please tell us if you accept the solution that has been proposed
[Testing_Plan_Result.docx](https://github.com/dianmoli98/ISII-WORKSHOPS-CLUB_POOL/files/5849666/Testing_Plan_Result.docx)

**Comment by lemendoza** [comment]
Is the same file as 'Testing_Plan' ... but I accept.

**Comment by dianmoli98** [comment]
The solution is complete. Now the programmer will release a new version. @lemendoza  @thsam

**Comment by thsam** [comment]
![image](https://user-images.githubusercontent.com/44647544/105390160-b871bf00-5be6-11eb-89d1-163a61f5819a.png)
To test the functionality we must place the given conditions, in this case, the test is done with respect to the new functionality. In this case we add a male client, his age is 41, not married and with a valid license
Do you agree with the solution? @lemendoza 
![image](https://user-images.githubusercontent.com/44647544/105391184-dbe93980-5be7-11eb-9882-df7f2df98b7e.png)

**Comment by lemendoza** [comment]
No. I do not agree. According to the new rule, pbase must be $200, shouldn't it?

**Comment by Diermanio** [comment]
No, it shouldn't according to our plan test that only should happen if our customer is also married, in this example is not married intentionally to show you what happen if only this new feature is fulfilled, if our costumer is also married then the pbase should be $200 @lemendoza

**Comment by lemendoza** [comment]
Ok. Please, continue. I agree with the solution.

**Comment by dianmoli98** [comment]
Are you satisfied with the proposed solution? If your answer is yes, the ticket will be closed. @lemendoza

**Comment by lemendoza** [comment]
Yes, I satisfied with the solution.
